<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tags = [
            [
                "tag_name" => "مدیریت ایمیل",
                "arabic_name" => "مدیریت ایمیل",
                "english_name" => "Email Handling",
                "slug" => "email-handling",
            ],
            [
                "tag_name" => "فتوشاپ",
                "arabic_name" => "فتوشاپ",
                "english_name" => "Photoshop",
                "slug" => "photoshop",
            ],
            [
                "tag_name" => "عربی",
                "arabic_name" => "عربی",
                "english_name" => "Arabic",
                "slug" => "arabic",
            ],
            [
                "tag_name" => "انگلیسی",
                "arabic_name" => "انگلیسی",
                "english_name" => "English",
                "slug" => "english",
            ],
            [
                "tag_name" => "طراحی فتوشاپ",
                "arabic_name" => "طراحی فتوشاپ",
                "english_name" => "Photoshop Design",
                "slug" => "photoshop-design",
            ],
            [
                "tag_name" => "Illustrator",
                "arabic_name" => "",
                "english_name" => "Illustrator",
                "slug" => "illustrator",
            ],
            [
                "tag_name" => "Microsoft Word",
                "arabic_name" => "",
                "english_name" => "Microsoft Word",
                "slug" => "microsoft-word",
            ],
            [
                "tag_name" => "طراحی لوگو",
                "arabic_name" => "طراحی لوگو",
                "english_name" => "Logo Design",
                "slug" => "logo-design",
            ],
            [
                "tag_name" => "طراحی گرافیک",
                "arabic_name" => "طراحی گرافیک",
                "english_name" => "Graphic Design",
                "slug" => "graphic-design",
            ],
            [
                "tag_name" => "بازنویسی مقاله",
                "arabic_name" => "بازنویسی مقاله",
                "english_name" => "Article Rewriting",
                "slug" => "article-rewriting",
            ],
            [
                "tag_name" => "طراحی خلاقانه",
                "arabic_name" => "طراحی خلاقانه",
                "english_name" => "Creative Design",
                "slug" => "creative-design",
            ],
            [
                "tag_name" => "ترجمه",
                "arabic_name" => "ترجمه",
                "english_name" => "Translation",
                "slug" => "translation",
            ],
            [
                "tag_name" => "طراحی تبلیغات",
                "arabic_name" => "طراحی تبلیغات",
                "english_name" => "Advertisement Design",
                "slug" => "advertisement-design",
            ],
            [
                "tag_name" => "ورود داده‌ها",
                "arabic_name" => "ورود داده‌ها",
                "english_name" => "Data Entry",
                "slug" => "data-entry",
            ],
            [
                "tag_name" => "Microsoft Office",
                "arabic_name" => "",
                "english_name" => "Microsoft Office",
                "slug" => "microsoft-office",
            ],
            [
                "tag_name" => "ویرایش عکس",
                "arabic_name" => "ویرایش عکس",
                "english_name" => "Photo Editing",
                "slug" => "photo-editing",
            ],
            [
                "tag_name" => "جستجوی وب",
                "arabic_name" => "جستجوی وب",
                "english_name" => "Web Search",
                "slug" => "web-search",
            ],
            [
                "tag_name" => "تحقیق اینترنتی",
                "arabic_name" => "تحقیق اینترنتی",
                "english_name" => "Internet Research",
                "slug" => "internet-research",
            ],
            [
                "tag_name" => "Microsoft Excel",
                "arabic_name" => "",
                "english_name" => "Microsoft Excel",
                "slug" => "excel",
            ],
            [
                "tag_name" => "طراحی پوستر",
                "arabic_name" => "طراحی پوستر",
                "english_name" => "Poster Design",
                "slug" => "poster-design",
            ],
            [
                "tag_name" => "HTML",
                "arabic_name" => "",
                "english_name" => "HTML",
                "slug" => "html",
            ],
            [
                "tag_name" => "CSS",
                "arabic_name" => "",
                "english_name" => "CSS",
                "slug" => "css",
            ],
            [
                "tag_name" => "نوشتن محتوا",
                "arabic_name" => "نوشتن محتوا",
                "english_name" => "Content Writing",
                "slug" => "content-writing",
            ],
            [
                "tag_name" => "اندروید",
                "arabic_name" => "اندروید",
                "english_name" => "Android",
                "slug" => "android",
            ],
            [
                "tag_name" => "PHP",
                "arabic_name" => "",
                "english_name" => "PHP",
                "slug" => "php",
            ],
            [
                "tag_name" => "طراحی بنر",
                "arabic_name" => "طراحی بنر",
                "english_name" => "Banner Design",
                "slug" => "banner-design",
            ],
            [
                "tag_name" => "PDF",
                "arabic_name" => "",
                "english_name" => "PDF",
                "slug" => "pdf",
            ],
            [
                "tag_name" => "مقالات",
                "arabic_name" => "مقالات",
                "english_name" => "Articles",
                "slug" => "articles",
            ],
            [
                "tag_name" => "بازاریابی اینترنتی",
                "arabic_name" => "بازاریابی اینترنتی",
                "english_name" => "Internet Marketing",
                "slug" => "internet-marketing",
            ],
            [
                "tag_name" => "طراحی مفهومی",
                "arabic_name" => "طراحی مفهومی",
                "english_name" => "Concept Design",
                "slug" => "concept-design",
            ],
            [
                "tag_name" => "نوشتن آنلاین",
                "arabic_name" => "نوشتن آنلاین",
                "english_name" => "Online Writing",
                "slug" => "online-writing",
            ],
            [
                "tag_name" => "تصحیح",
                "arabic_name" => "تصحیح",
                "english_name" => "Proofreading",
                "slug" => "proofreading",
            ],
            [
                "tag_name" => "طراحی وب‌سایت",
                "arabic_name" => "طراحی وب‌سایت",
                "english_name" => "Website Design",
                "slug" => "website-design",
            ],
            [
                "tag_name" => "تولید ویدیو",
                "arabic_name" => "تولید ویدیو",
                "english_name" => "Video Production",
                "slug" => "video-production",
            ],
            [
                "tag_name" => "طراحی دعوتنامه",
                "arabic_name" => "طراحی دعوتنامه",
                "english_name" => "Invitation Design",
                "slug" => "invitation-design",
            ],
            [
                "tag_name" => "بازاریابی فیسبوک",
                "arabic_name" => "بازاریابی فیسبوک",
                "english_name" => "Facebook Marketing",
                "slug" => "facebook-marketing",
            ],
            [
                "tag_name" => "تحقیق",
                "arabic_name" => "تحقیق",
                "english_name" => "Research",
                "slug" => "research",
            ],
            [
                "tag_name" => "بازاریابی",
                "arabic_name" => "بازاریابی",
                "english_name" => "Marketing",
                "slug" => "marketing",
            ],
            [
                "tag_name" => "فرانسوی",
                "arabic_name" => "فرانسوی",
                "english_name" => "French",
                "slug" => "french",
            ],
            [
                "tag_name" => "ویرایش",
                "arabic_name" => "ویرایش",
                "english_name" => "Editing",
                "slug" => "editing",
            ],
            [
                "tag_name" => "جاوااسکریپت",
                "arabic_name" => "جاوااسکریپت",
                "english_name" => "Javascript",
                "slug" => "javascript",
            ],
            [
                "tag_name" => "پاورپوینت",
                "arabic_name" => "",
                "english_name" => "Powerpoint",
                "slug" => "powerpoint",
            ],
            [
                "tag_name" => "نوشتن گزارش",
                "arabic_name" => "نوشتن گزارش",
                "english_name" => "Report Writing",
                "slug" => "report-writing",
            ],
            [
                "tag_name" => "After Effects",
                "arabic_name" => "",
                "english_name" => "After Effects",
                "slug" => "after-effects",
            ],
            [
                "tag_name" => "نوشتن خلاقانه",
                "arabic_name" => "نوشتن خلاقانه",
                "english_name" => "Creative Writing",
                "slug" => "creative-writing",
            ],
            [
                "tag_name" => "آموزش و تدریس خصوصی",
                "arabic_name" => "آموزش و تدریس خصوصی",
                "english_name" => "Education & Tutoring",
                "slug" => "education-tutoring",
            ],
            [
                "tag_name" => "طراحی برچسب",
                "arabic_name" => "طراحی برچسب",
                "english_name" => "Label Design",
                "slug" => "label-design",
            ],
            [
                "tag_name" => "Bootstrap",
                "arabic_name" => "",
                "english_name" => "Bootstrap",
                "slug" => "bootstrap",
            ],
            [
                "tag_name" => "وردپرس",
                "arabic_name" => "وردپرس",
                "english_name" => "Wordpress",
                "slug" => "wordpress",
            ],
            [
                "tag_name" => "jQuery",
                "arabic_name" => "",
                "english_name" => "jQuery",
                "slug" => "jquery",
            ],
            [
                "tag_name" => "طراحی 3D",
                "arabic_name" => "طراحی 3D",
                "english_name" => "3D Design",
                "slug" => "3d-design",
            ],
            [
                "tag_name" => "بازاریابی شبکه‌های اجتماعی",
                "arabic_name" => "بازاریابی شبکه‌های اجتماعی",
                "english_name" => "Social Media Marketing",
                "slug" => "social-media-marketing",
            ],
            [
                "tag_name" => "ویرایش ویدیو",
                "arabic_name" => "ویرایش ویدیو",
                "english_name" => "Video Editing",
                "slug" => "video-editing",
            ],
            [
                "tag_name" => "MySQL",
                "arabic_name" => "",
                "english_name" => "MySQL",
                "slug" => "mysql",
            ],
            [
                "tag_name" => "تبلیغات",
                "arabic_name" => "تبلیغات",
                "english_name" => "Advertising",
                "slug" => "advertising",
            ],
            [
                "tag_name" => "پردازش کلمات",
                "arabic_name" => "پردازش کلمات",
                "english_name" => "Word Processing",
                "slug" => "word-processing",
            ],
            [
                "tag_name" => "ورزش",
                "arabic_name" => "ورزش",
                "english_name" => "Sports",
                "slug" => "sports",
            ],
            [
                "tag_name" => "گرامر انگلیسی",
                "arabic_name" => "گرامر انگلیسی",
                "english_name" => "English Grammar",
                "slug" => "english-grammar",
            ],
            [
                "tag_name" => "عکاسی",
                "arabic_name" => "عکاسی",
                "english_name" => "Photography",
                "slug" => "photography",
            ],
            [
                "tag_name" => "املا انگلیسی",
                "arabic_name" => "املا انگلیسی",
                "english_name" => "English Spelling",
                "slug" => "english-spelling",
            ],
            [
                "tag_name" => "اتوکد",
                "arabic_name" => "اتوکد",
                "english_name" => "AutoCAD",
                "slug" => "autocad",
            ],
            [
                "tag_name" => "مدیریت",
                "arabic_name" => "مدیریت",
                "english_name" => "Management",
                "slug" => "management",
            ],
            [
                "tag_name" => "وبلاگ نویسی",
                "arabic_name" => "وبلاگ نویسی",
                "english_name" => "Blogging",
                "slug" => "blogging",
            ],
            [
                "tag_name" => "DS ماکس",
                "arabic_name" => "",
                "english_name" => "",
                "slug" => "DS ماکس",
            ],
            [
                "tag_name" => "طراحی آیکون",
                "arabic_name" => "طراحی آیکون",
                "english_name" => "Icon Design",
                "slug" => "icon-design",
            ],
            [
                "tag_name" => "کارت ویزیت",
                "arabic_name" => "کارت ویزیت",
                "english_name" => "Business Cards",
                "slug" => "business-cards",
            ],
            [
                "tag_name" => "حسابداری",
                "arabic_name" => "حسابداری",
                "english_name" => "Accounting",
                "slug" => "accounting",
            ],
            [
                "tag_name" => "رزومه",
                "arabic_name" => "رزومه",
                "english_name" => "Resumes",
                "slug" => "resumes",
            ],
            [
                "tag_name" => "تایپ",
                "arabic_name" => "تایپ",
                "english_name" => "Copy Typing",
                "slug" => "copy-typing",
            ],
            [
                "tag_name" => "داستان کوتاه",
                "arabic_name" => "داستان کوتاه",
                "english_name" => "Short Stories",
                "slug" => "short-stories",
            ],
            [
                "tag_name" => "پشتیبانی مشتری",
                "arabic_name" => "پشتیبانی مشتری",
                "english_name" => "Customer Support",
                "slug" => "customer-support",
            ],
            [
                "tag_name" => "مدیریت پروژه",
                "arabic_name" => "مدیریت پروژه",
                "english_name" => "Project Management",
                "slug" => "project-management",
            ],
            [
                "tag_name" => "کپی رایتینگ",
                "arabic_name" => "کپی رایتینگ",
                "english_name" => "Copywriting",
                "slug" => "copywriting",
            ],
            [
                "tag_name" => "عیب‌یابی",
                "arabic_name" => "عیب‌یابی",
                "english_name" => "Troubleshooting",
                "slug" => "troubleshooting",
            ],
            [
                "tag_name" => "طراحی بروشور",
                "arabic_name" => "طراحی بروشور",
                "english_name" => "Brochure Design",
                "slug" => "brochure-design",
            ],
            [
                "tag_name" => "بازاریابی وابسته",
                "arabic_name" => "بازاریابی وابسته",
                "english_name" => "Affiliate Marketing",
                "slug" => "affiliate-marketing",
            ],
            [
                "tag_name" => "آشپزی و دستور پخت",
                "arabic_name" => "آشپزی و دستور پخت",
                "english_name" => "Cooking & Recipes",
                "slug" => "cooking-recipes",
            ],
            [
                "tag_name" => "Adobe InDesign",
                "arabic_name" => "",
                "english_name" => "Adobe InDesign",
                "slug" => "adobe-indesign",
            ],
            [
                "tag_name" => "طراحی استیکر",
                "arabic_name" => "طراحی استیکر",
                "english_name" => "Sticker Design",
                "slug" => "sticker-design",
            ],
            [
                "tag_name" => "آموزش",
                "arabic_name" => "آموزش",
                "english_name" => "Training",
                "slug" => "training",
            ],
            [
                "tag_name" => "ارسال مقاله",
                "arabic_name" => "ارسال مقاله",
                "english_name" => "Article Submission",
                "slug" => "article-submission",
            ],
            [
                "tag_name" => "حسابرسی",
                "arabic_name" => "حسابرسی",
                "english_name" => "Audit",
                "slug" => "audit",
            ],
            [
                "tag_name" => "توسعه نرم‌افزار",
                "arabic_name" => "توسعه نرم‌افزار",
                "english_name" => "Software Development",
                "slug" => "software-development",
            ],
            [
                "tag_name" => "برنامه‌نویسی پایگاه داده",
                "arabic_name" => "برنامه‌نویسی پایگاه داده",
                "english_name" => "Database Programming",
                "slug" => "database-programming",
            ],
            [
                "tag_name" => "جاوا",
                "arabic_name" => "جاوا",
                "english_name" => "Java",
                "slug" => "java",
            ],
            [
                "tag_name" => "آیفون",
                "arabic_name" => "آیفون",
                "english_name" => "iPhone",
                "slug" => "iphone",
            ],
            [
                "tag_name" => "مدیریت زمان",
                "arabic_name" => "مدیریت زمان",
                "english_name" => "Time Management",
                "slug" => "time-management",
            ],
            [
                "tag_name" => "مربی زندگی",
                "arabic_name" => "مربی زندگی",
                "english_name" => "Life Coaching",
                "slug" => "life-coaching",
            ],
            [
                "tag_name" => "برنامه‌نویسی C#",
                "arabic_name" => "",
                "english_name" => "C# Programming",
                "slug" => "csharp-programming",
            ],
            [
                "tag_name" => "فروش",
                "arabic_name" => "فروش",
                "english_name" => "Sales",
                "slug" => "sales",
            ],
            [
                "tag_name" => "ویرایش کتاب",
                "arabic_name" => "ویرایش کتاب",
                "english_name" => "Book Editing",
                "slug" => "book-editing",
            ],
            [
                "tag_name" => "هویت سازمانی",
                "arabic_name" => "هویت سازمانی",
                "english_name" => "Corporate Identity",
                "slug" => "corporate-identity",
            ],
            [
                "tag_name" => "خدمات ویدیو",
                "arabic_name" => "خدمات ویدیو",
                "english_name" => "Video Services",
                "slug" => "video-services",
            ],
            [
                "tag_name" => "طراحی داخلی",
                "arabic_name" => "طراحی داخلی",
                "english_name" => "Interior Design",
                "slug" => "interior-design",
            ],
            [
                "tag_name" => "چاپ",
                "arabic_name" => "چاپ",
                "english_name" => "Print",
                "slug" => "print",
            ],
            [
                "tag_name" => "مدل‌سازی 3D",
                "arabic_name" => "مدل‌سازی 3D",
                "english_name" => "3D Modelling",
                "slug" => "3d-modelling",
            ],
            [
                "tag_name" => "پردازش داده‌ها",
                "arabic_name" => "پردازش داده‌ها",
                "english_name" => "Data Processing",
                "slug" => "data-processing",
            ],
            [
                "tag_name" => "وبلاگ",
                "arabic_name" => "وبلاگ",
                "english_name" => "Blog",
                "slug" => "blog",
            ],
            [
                "tag_name" => "بازاریابی تلفنی",
                "arabic_name" => "بازاریابی تلفنی",
                "english_name" => "Telemarketing",
                "slug" => "telemarketing",
            ],
            [
                "tag_name" => "سلامت",
                "arabic_name" => "سلامت",
                "english_name" => "Health",
                "slug" => "health",
            ],
            [
                "tag_name" => "نوشتن تجاری",
                "arabic_name" => "نوشتن تجاری",
                "english_name" => "Business Writing",
                "slug" => "business-writing",
            ],
            [
                "tag_name" => "AJAX",
                "arabic_name" => "",
                "english_name" => "AJAX",
                "slug" => "ajax",
            ],
            [
                "tag_name" => "ارائه‌ها",
                "arabic_name" => "ارائه‌ها",
                "english_name" => "Presentations",
                "slug" => "presentations",
            ],
            [
                "tag_name" => "SQL",
                "arabic_name" => "",
                "english_name" => "SQL",
                "slug" => "sql",
            ],
            [
                "tag_name" => "نوشتن آکادمیک",
                "arabic_name" => "نوشتن آکادمیک",
                "english_name" => "Academic Writing",
                "slug" => "academic-writing",
            ],
            [
                "tag_name" => "تلفن همراه",
                "arabic_name" => "تلفن همراه",
                "english_name" => "Mobile Phone",
                "slug" => "mobile-phone",
            ],
            [
                "tag_name" => "تحقیق علمی",
                "arabic_name" => "تحقیق علمی",
                "english_name" => "Scientific Research",
                "slug" => "scientific-research",
            ],
            [
                "tag_name" => "مالی",
                "arabic_name" => "مالی",
                "english_name" => "Finance",
                "slug" => "finance",
            ],
            [
                "tag_name" => "سامسونگ",
                "arabic_name" => "سامسونگ",
                "english_name" => "Samsung",
                "slug" => "samsung",
            ],
            [
                "tag_name" => "Microsoft Outlook",
                "arabic_name" => "",
                "english_name" => "Microsoft Outlook",
                "slug" => "microsoft-outlook",
            ],
            [
                "tag_name" => "یوتیوب",
                "arabic_name" => "یوتیوب",
                "english_name" => "YouTube",
                "slug" => "youtube",
            ],
            [
                "tag_name" => "کتاب‌های الکترونیکی",
                "arabic_name" => "کتاب‌های الکترونیکی",
                "english_name" => "eBooks",
                "slug" => "ebooks",
            ],
            [
                "tag_name" => "طراحی فلایر",
                "arabic_name" => "طراحی فلایر",
                "english_name" => "Flyer Design",
                "slug" => "flyer-design",
            ],
            [
                "tag_name" => "بازاریابی ایمیلی",
                "arabic_name" => "بازاریابی ایمیلی",
                "english_name" => "Email Marketing",
                "slug" => "email-marketing",
            ],
            [
                "tag_name" => "شعارها",
                "arabic_name" => "شعارها",
                "english_name" => "Slogans",
                "slug" => "slogans",
            ],
            [
                "tag_name" => "عبارات معروف",
                "arabic_name" => "عبارات معروف",
                "english_name" => "Catch Phrases",
                "slug" => "catch-phrases",
            ],
            [
                "tag_name" => "منابع انسانی",
                "arabic_name" => "منابع انسانی",
                "english_name" => "Human Resources",
                "slug" => "human-resources",
            ],
            [
                "tag_name" => "نوشتن سخنرانی",
                "arabic_name" => "نوشتن سخنرانی",
                "english_name" => "Speech Writing",
                "slug" => "speech-writing",
            ],
            [
                "tag_name" => "طراحی بسته‌بندی",
                "arabic_name" => "طراحی بسته‌بندی",
                "english_name" => "Package Design",
                "slug" => "package-design",
            ],
            [
                "tag_name" => "PSD to HTML",
                "arabic_name" => "",
                "english_name" => "PSD to HTML",
                "slug" => "psd-to-html",
            ],
            [
                "tag_name" => "معماری ساختمان",
                "arabic_name" => "معماری ساختمان",
                "english_name" => "Building Architecture",
                "slug" => "building-architecture",
            ],
            [
                "tag_name" => "روابط عمومی",
                "arabic_name" => "روابط عمومی",
                "english_name" => "Public Relations",
                "slug" => "public-relations",
            ],
            [
                "tag_name" => "برنامه‌های تجاری",
                "arabic_name" => "برنامه‌های تجاری",
                "english_name" => "Business Plans",
                "slug" => "business-plans",
            ],
            [
                "tag_name" => "موشن گرافیک",
                "arabic_name" => "موشن گرافیک",
                "english_name" => "Motion Graphics",
                "slug" => "موشن گرافیک",
            ],
            [
                "tag_name" => "ریاضیات",
                "arabic_name" => "ریاضیات",
                "english_name" => "Mathematics",
                "slug" => "mathematics",
            ],
            [
                "tag_name" => "روانشناسی",
                "arabic_name" => "روانشناسی",
                "english_name" => "Psychology",
                "slug" => "psychology",
            ],
            [
                "tag_name" => "توسعه شخصی",
                "arabic_name" => "توسعه شخصی",
                "english_name" => "Personal Development",
                "slug" => "personal-development",
            ],
            [
                "tag_name" => "نوشتن کتاب",
                "arabic_name" => "نوشتن کتاب",
                "english_name" => "Book Writing",
                "slug" => "book-writing",
            ],
            [
                "tag_name" => "برنامه‌نویسی C++",
                "arabic_name" => "",
                "english_name" => "C++ Programming",
                "slug" => "cpp-programming",
            ],
            [
                "tag_name" => "شعر",
                "arabic_name" => "شعر",
                "english_name" => "Poetry",
                "slug" => "poetry",
            ],
            [
                "tag_name" => "تحلیل کسب و کار",
                "arabic_name" => "تحلیل کسب و کار",
                "english_name" => "Business Analysis",
                "slug" => "business-analysis",
            ],
            [
                "tag_name" => "ASP.NET",
                "arabic_name" => "",
                "english_name" => "ASP.NET",
                "slug" => "asp-net",
            ],
            [
                "tag_name" => "مدیریت وب‌سایت",
                "arabic_name" => "مدیریت وب‌سایت",
                "english_name" => "Website Management",
                "slug" => "website-management",
            ],
            [
                "tag_name" => "Laravel",
                "arabic_name" => "",
                "english_name" => "Laravel",
                "slug" => "laravel",
            ],
            [
                "tag_name" => "تغذیه",
                "arabic_name" => "تغذیه",
                "english_name" => "Nutrition",
                "slug" => "nutrition",
            ],
            [
                "tag_name" => "انیمیشن",
                "arabic_name" => "انیمیشن",
                "english_name" => "Animation",
                "slug" => "animation",
            ],
            [
                "tag_name" => "بازاریابی موتور جستجو",
                "arabic_name" => "بازاریابی موتور جستجو",
                "english_name" => "Search Engine Marketing",
                "slug" => "search-engine-marketing",
            ],
            [
                "tag_name" => "ویکی‌پدیا",
                "arabic_name" => "ویکی‌پدیا",
                "english_name" => "Wikipedia",
                "slug" => "wikipedia",
            ],
            [
                "tag_name" => "نوشتن فیلمنامه",
                "arabic_name" => "نوشتن فیلمنامه",
                "english_name" => "Screenwriting",
                "slug" => "screenwriting",
            ],
            [
                "tag_name" => "مدیریت پایگاه داده",
                "arabic_name" => "مدیریت پایگاه داده",
                "english_name" => "Database Administration",
                "slug" => "database-administration",
            ],
            [
                "tag_name" => "کارآفرینی",
                "arabic_name" => "کارآفرینی",
                "english_name" => "Entrepreneurship",
                "slug" => "entrepreneurship",
            ],
            [
                "tag_name" => "نوشتن پیشنهاد/درخواست",
                "arabic_name" => "نوشتن پیشنهاد/درخواست",
                "english_name" => "Proposal/Bid Writing",
                "slug" => "proposal-bid-writing",
            ],
            [
                "tag_name" => "حسابداری",
                "arabic_name" => "حسابداری",
                "english_name" => "Bookkeeping",
                "slug" => "bookkeeping",
            ],
            [
                "tag_name" => "هنر و صنایع دستی",
                "arabic_name" => "هنر و صنایع دستی",
                "english_name" => "Arts & Crafts",
                "slug" => "arts-crafts",
            ],
            [
                "tag_name" => "Microsoft SQL Server",
                "arabic_name" => "",
                "english_name" => "Microsoft SQL Server",
                "slug" => "microsoft-sql-server",
            ],
            [
                "tag_name" => "طراحی وبلاگ",
                "arabic_name" => "طراحی وبلاگ",
                "english_name" => "Blog Design",
                "slug" => "blog-design",
            ],
            [
                "tag_name" => "مدیریت ارتباط با مشتری",
                "arabic_name" => "مدیریت ارتباط با مشتری",
                "english_name" => "CRM",
                "slug" => "crm",
            ],
            [
                "tag_name" => "تاریخ",
                "arabic_name" => "تاریخ",
                "english_name" => "History",
                "slug" => "history",
            ],
            [
                "tag_name" => "صداگذاری",
                "arabic_name" => "صداگذاری",
                "english_name" => "Voice Over",
                "slug" => "voice-over",
            ],
            [
                "tag_name" => "تحقیق بازار",
                "arabic_name" => "تحقیق بازار",
                "english_name" => "Market Research",
                "slug" => "market-research",
            ],
            [
                "tag_name" => "برندسازی",
                "arabic_name" => "برندسازی",
                "english_name" => "Branding",
                "slug" => "branding",
            ],
            [
                "tag_name" => "مهندسی",
                "arabic_name" => "مهندسی",
                "english_name" => "Engineering",
                "slug" => "engineering",
            ],
            [
                "tag_name" => "Google Adsense",
                "arabic_name" => "Google Adsense",
                "english_name" => "Google Adsense",
                "slug" => "google-adsense",
            ],
            [
                "tag_name" => "مدیریت موجودی",
                "arabic_name" => "مدیریت موجودی",
                "english_name" => "Inventory Management",
                "slug" => "inventory-management",
            ],
            [
                "tag_name" => "دستیار مجازی",
                "arabic_name" => "دستیار مجازی",
                "english_name" => "Virtual Assistant",
                "slug" => "virtual-assistant",
            ],
            [
                "tag_name" => "معماری نرم‌افزار",
                "arabic_name" => "معماری نرم‌افزار",
                "english_name" => "Software Architecture",
                "slug" => "software-architecture",
            ],
            [
                "tag_name" => "پشتیبانی تلفنی",
                "arabic_name" => "پشتیبانی تلفنی",
                "english_name" => "Phone Support",
                "slug" => "phone-support",
            ],
            [
                "tag_name" => "تجارت الکترونیک",
                "arabic_name" => "تجارت الکترونیک",
                "english_name" => "eCommerce",
                "slug" => "ecommerce",
            ],
            [
                "tag_name" => "برنامه‌ریزی رویداد",
                "arabic_name" => "برنامه‌ریزی رویداد",
                "english_name" => "Event Planning",
                "slug" => "event-planning",
            ],
            [
                "tag_name" => "ارسال آگهی‌های طبقه‌بندی شده",
                "arabic_name" => "ارسال آگهی‌های طبقه‌بندی شده",
                "english_name" => "Classifieds Posting",
                "slug" => "classifieds-posting",
            ],
            [
                "tag_name" => "تولید صدا",
                "arabic_name" => "تولید صدا",
                "english_name" => "Audio Production",
                "slug" => "audio-production",
            ],
            [
                "tag_name" => "طوفان فکری",
                "arabic_name" => "طوفان فکری",
                "english_name" => "Brain Storming",
                "slug" => "brain-storming",
            ],
            [
                "tag_name" => "رندرینگ 3D",
                "arabic_name" => "رندرینگ 3D",
                "english_name" => "3D Rendering",
                "slug" => "3d-rendering",
            ],
            [
                "tag_name" => "گرافیک متحرک",
                "arabic_name" => "گرافیک متحرک",
                "english_name" => "Motion Graphics",
                "slug" => "motion-graphics",
            ],
            [
                "tag_name" => "انتشار",
                "arabic_name" => "انتشار",
                "english_name" => "Publishing",
                "slug" => "publishing",
            ],
            [
                "tag_name" => "تبلیغات حسوب",
                "arabic_name" => "تبلیغات حسوب",
                "english_name" => "Hsoub Ads",
                "slug" => "hsoub-ads",
            ],
            [
                "tag_name" => "الکترونیک",
                "arabic_name" => "الکترونیک",
                "english_name" => "Electronics",
                "slug" => "electronics",
            ],
            [
                "tag_name" => "نوشتن فنی",
                "arabic_name" => "نوشتن فنی",
                "english_name" => "Technical Writing",
                "slug" => "technical-writing",
            ],
            [
                "tag_name" => "تحلیل مالی",
                "arabic_name" => "تحلیل مالی",
                "english_name" => "Financial Analysis",
                "slug" => "financial-analysis",
            ],
            [
                "tag_name" => "نوشتن پزشکی",
                "arabic_name" => "نوشتن پزشکی",
                "english_name" => "Medical Writing",
                "slug" => "medical-writing",
            ],
            [
                "tag_name" => "کاریکاتور و کارتون",
                "arabic_name" => "کاریکاتور و کارتون",
                "english_name" => "Caricature & Cartoons",
                "slug" => "caricature-cartoons",
            ],
            [
                "tag_name" => "مربی کسب و کار",
                "arabic_name" => "مربی کسب و کار",
                "english_name" => "Business Coaching",
                "slug" => "business-coaching",
            ],
            [
                "tag_name" => "تایپوگرافی",
                "arabic_name" => "تایپوگرافی",
                "english_name" => "Typography",
                "slug" => "typography",
            ],
            [
                "tag_name" => "قالب‌ها",
                "arabic_name" => "قالب‌ها",
                "english_name" => "Templates",
                "slug" => "templates",
            ],
            [
                "tag_name" => "انیمیشن 3D",
                "arabic_name" => "انیمیشن 3D",
                "english_name" => "3D Animation",
                "slug" => "3d-animation",
            ],
            [
                "tag_name" => "موسیقی",
                "arabic_name" => "موسیقی",
                "english_name" => "Music",
                "slug" => "music",
            ],
            [
                "tag_name" => "پوشش‌ها و بسته‌بندی",
                "arabic_name" => "پوشش‌ها و بسته‌بندی",
                "english_name" => "Covers & Packaging",
                "slug" => "covers-packaging",
            ],
            [
                "tag_name" => "خدمات صوتی",
                "arabic_name" => "خدمات صوتی",
                "english_name" => "Audio Services",
                "slug" => "audio-services",
            ],
            [
                "tag_name" => "طراحی مبلمان",
                "arabic_name" => "طراحی مبلمان",
                "english_name" => "Furniture Design",
                "slug" => "furniture-design",
            ],
            [
                "tag_name" => "آیپد",
                "arabic_name" => "آیپد",
                "english_name" => "iPad",
                "slug" => "ipad",
            ],
            [
                "tag_name" => "IOS",
                "arabic_name" => "",
                "english_name" => "IOS",
                "slug" => "IOS",
            ],
            [
                "tag_name" => "برنامه‌نویسی C",
                "arabic_name" => "",
                "english_name" => "C Programming",
                "slug" => "c-programming",
            ],
            [
                "tag_name" => "طراحی خانه",
                "arabic_name" => "طراحی خانه",
                "english_name" => "Home Design",
                "slug" => "home-design",
            ],
            [
                "tag_name" => "توسعه پایگاه داده",
                "arabic_name" => "توسعه پایگاه داده",
                "english_name" => "Database Development",
                "slug" => "database-development",
            ],
            [
                "tag_name" => "شبکه‌های اجتماعی",
                "arabic_name" => "شبکه‌های اجتماعی",
                "english_name" => "Social Networking",
                "slug" => "social-networking",
            ],
            [
                "tag_name" => "عروسی‌ها",
                "arabic_name" => "عروسی‌ها",
                "english_name" => "Weddings",
                "slug" => "weddings",
            ],
            [
                "tag_name" => "قراردادها",
                "arabic_name" => "قراردادها",
                "english_name" => "Contracts",
                "slug" => "contracts",
            ],
            [
                "tag_name" => "Adobe Flash",
                "arabic_name" => "",
                "english_name" => "Adobe Flash",
                "slug" => "adobe-flash",
            ],
            [
                "tag_name" => "استخراج داده‌ها",
                "arabic_name" => "استخراج داده‌ها",
                "english_name" => "Data Mining",
                "slug" => "data-mining",
            ],
            [
                "tag_name" => "املاک و مستغلات",
                "arabic_name" => "املاک و مستغلات",
                "english_name" => "Real Estate",
                "slug" => "real-estate",
            ],
            [
                "tag_name" => "Google SketchUp",
                "arabic_name" => "",
                "english_name" => "Google SketchUp",
                "slug" => "google-sketchup",
            ],
            [
                "tag_name" => "انتشار مطبوعات",
                "arabic_name" => "انتشار مطبوعات",
                "english_name" => "Press Releases",
                "slug" => "press-releases",
            ],
            [
                "tag_name" => "بررسی‌ها",
                "arabic_name" => "بررسی‌ها",
                "english_name" => "Reviews",
                "slug" => "reviews",
            ],
            [
                "tag_name" => "تست اپلیکیشن موبایل",
                "arabic_name" => "تست اپلیکیشن موبایل",
                "english_name" => "Mobile App Testing",
                "slug" => "mobile-app-testing",
            ],
            [
                "tag_name" => "میزبانی وب",
                "arabic_name" => "میزبانی وب",
                "english_name" => "Web Hosting",
                "slug" => "web-hosting",
            ],
            [
                "tag_name" => "سیستم‌های مدیریت محتوا",
                "arabic_name" => "سیستم‌های مدیریت محتوا",
                "english_name" => "CMS",
                "slug" => "cms",
            ],
            [
                "tag_name" => "استعداد صدا",
                "arabic_name" => "استعداد صدا",
                "english_name" => "Voice Talent",
                "slug" => "voice-talent",
            ],
            [
                "tag_name" => "استخدام",
                "arabic_name" => "استخدام",
                "english_name" => "Recruitment",
                "slug" => "recruitment",
            ],
            [
                "tag_name" => "قانونی",
                "arabic_name" => "قانونی",
                "english_name" => "Legal",
                "slug" => "legal",
            ],
            [
                "tag_name" => "Google Adwords",
                "arabic_name" => "Google Adwords",
                "english_name" => "Google Adwords",
                "slug" => "google-adwords",
            ],
            [
                "tag_name" => "پردازش سفارشات",
                "arabic_name" => "پردازش سفارشات",
                "english_name" => "Order Processing",
                "slug" => "order-processing",
            ],
            [
                "tag_name" => "خبرنامه‌ها",
                "arabic_name" => "خبرنامه‌ها",
                "english_name" => "Newsletters",
                "slug" => "newsletters",
            ],
            [
                "tag_name" => "MVC",
                "arabic_name" => "",
                "english_name" => "MVC",
                "slug" => "mvc",
            ],
            [
                "tag_name" => "آموزش الکترونیکی",
                "arabic_name" => "آموزش الکترونیکی",
                "english_name" => "eLearning",
                "slug" => "elearning",
            ],
            [
                "tag_name" => "فرمت و چیدمان",
                "arabic_name" => "فرمت و چیدمان",
                "english_name" => "Format & Layout",
                "slug" => "format-layout",
            ],
            [
                "tag_name" => "Adobe Premiere",
                "arabic_name" => "",
                "english_name" => "Adobe Premiere",
                "slug" => "Adobe-Premiere",
            ],
            [
                "tag_name" => "SEO",
                "arabic_name" => "SEO",
                "english_name" => "SEO",
                "slug" => "seo",
            ],
            [
                "tag_name" => "Microsoft .NET",
                "arabic_name" => "",
                "english_name" => "Microsoft .NET",
                "slug" => "dot-net",
            ],
            [
                "tag_name" => "امنیت وب",
                "arabic_name" => "امنیت وب",
                "english_name" => "Web Security",
                "slug" => "web-security",
            ],
            [
                "tag_name" => "تصویرسازی",
                "arabic_name" => "تصویرسازی",
                "english_name" => "Illustration",
                "slug" => "illustration",
            ],
            [
                "tag_name" => "طراحی مد",
                "arabic_name" => "طراحی مد",
                "english_name" => "Fashion Design",
                "slug" => "fashion-design",
            ],
            [
                "tag_name" => "ارتباطات",
                "arabic_name" => "ارتباطات",
                "english_name" => "Communications",
                "slug" => "communications",
            ],
            [
                "tag_name" => "ERP",
                "arabic_name" => "",
                "english_name" => "ERP",
                "slug" => "erp",
            ],
            [
                "tag_name" => "برنامه‌ریزی و خرید تبلیغات",
                "arabic_name" => "برنامه‌ریزی و خرید تبلیغات",
                "english_name" => "Ad Planning & Buying",
                "slug" => "ad-planning-buying",
            ],
            [
                "tag_name" => "قانون کار",
                "arabic_name" => "قانون کار",
                "english_name" => "Employment Law",
                "slug" => "employment-law",
            ],
            [
                "tag_name" => "هنرهای بصری",
                "arabic_name" => "هنرهای بصری",
                "english_name" => "Visual Arts",
                "slug" => "visual-arts",
            ],
            [
                "tag_name" => "Autodesk Revit",
                "arabic_name" => "",
                "english_name" => "Autodesk Revit",
                "slug" => "autodesk-revit",
            ],
            [
                "tag_name" => "Adobe Dreamweaver",
                "arabic_name" => "",
                "english_name" => "Adobe Dreamweaver",
                "slug" => "adobe-dreamweaver",
            ],
            [
                "tag_name" => "مهندسی برق",
                "arabic_name" => "مهندسی برق",
                "english_name" => "Electrical Engineering",
                "slug" => "electrical-engineering",
            ],
            [
                "tag_name" => "XML",
                "arabic_name" => "",
                "english_name" => "XML",
                "slug" => "xml",
            ],
            [
                "tag_name" => "الگوریتم‌ها",
                "arabic_name" => "الگوریتم‌ها",
                "english_name" => "Algorithms",
                "slug" => "algorithms",
            ],
            [
                "tag_name" => "تحقیق قانونی",
                "arabic_name" => "تحقیق قانونی",
                "english_name" => "Legal Research",
                "slug" => "legal-research",
            ],
            [
                "tag_name" => "تست وب‌سایت",
                "arabic_name" => "تست وب‌سایت",
                "english_name" => "Website Testing",
                "slug" => "website-testing",
            ],
            [
                "tag_name" => "نوشتن قانونی",
                "arabic_name" => "نوشتن قانونی",
                "english_name" => "Legal Writing",
                "slug" => "legal-writing",
            ],
            [
                "tag_name" => "آلمانی",
                "arabic_name" => "آلمانی",
                "english_name" => "German",
                "slug" => "german",
            ],
            [
                "tag_name" => "Angular.js",
                "arabic_name" => "",
                "english_name" => "Angular.js",
                "slug" => "angular-js",
            ],
            [
                "tag_name" => "اشکال‌زدایی",
                "arabic_name" => "اشکال‌زدایی",
                "english_name" => "Debugging",
                "slug" => "debugging",
            ],
            [
                "tag_name" => "استارتاپ‌ها",
                "arabic_name" => "استارتاپ‌ها",
                "english_name" => "Startups",
                "slug" => "startups",
            ],
            [
                "tag_name" => "تحقیق سرمایه‌گذاری",
                "arabic_name" => "تحقیق سرمایه‌گذاری",
                "english_name" => "Investment Research",
                "slug" => "investment-research",
            ],
            [
                "tag_name" => "مدیریت املاک",
                "arabic_name" => "مدیریت املاک",
                "english_name" => "Property Management",
                "slug" => "property-management",
            ],
            [
                "tag_name" => "Microsoft Access",
                "arabic_name" => "",
                "english_name" => "Microsoft Access",
                "slug" => "microsoft-access",
            ],
            [
                "tag_name" => "خدمات وب",
                "arabic_name" => "خدمات وب",
                "english_name" => "Web Services",
                "slug" => "web-services",],
                [
                "tag_name" => "تست نرم‌افزار",
                "arabic_name" => "تست نرم‌افزار",
                "english_name" => "Software Testing",
                "slug" => "software-testing",
                ],
                [
                "tag_name" => "طراحی تجربه کاربری",
                "arabic_name" => "طراحی تجربه کاربری",
                "english_name" => "User Experience Design",
                "slug" => "user-experience-design",
                ],
                [
                "tag_name" => "میز کمک",
                "arabic_name" => "میز کمک",
                "english_name" => "Helpdesk",
                "slug" => "helpdesk",
                ],
                [
                "tag_name" => "اینفوگرافیک",
                "arabic_name" => "اینفوگرافیک",
                "english_name" => "Infographics",
                "slug" => "infographics",
                ],
                [
                "tag_name" => "CSS Sass",
                "arabic_name" => "",
                "english_name" => "CSS Sass",
                "slug" => "sass",
                ],
                [
                "tag_name" => "انبار داده‌ها",
                "arabic_name" => "انبار داده‌ها",
                "english_name" => "Data Warehousing",
                "slug" => "data-warehousing",
                ],
                [
                "tag_name" => "فیزیک",
                "arabic_name" => "فیزیک",
                "english_name" => "Physics",
                "slug" => "physics",
                ],

        ];
        //\App\Models\Tag::truncate();
        \App\Models\Tag::insert( collect($tags)->unique('slug')->all() );

    }
}
