apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dashboard
  namespace: general-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: dash.peterayoub.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dashboard
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dashboard
            port:
              number: 443
  - host: www.dash.peterayoub.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dashboard
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-dashboard
            port:
              number: 443
  tls:
    - hosts:
      - dash.peterayoub.me
      - www.dash.peterayoub.me
      secretName: dashboard-com-tls