apiVersion: v1
kind: PersistentVolume
metadata:
  name: dashbaord-pv
  namespace: general-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-storage"
  nfs:
    path: /home/ubuntu/shared/
    server: 10.7.112.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashbaord-pvc
  namespace: general-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-storage"